/* Additional record code for Reference_1 generated by the OpenModelica Compiler OpenModelica 1.18.0. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "Reference_1_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Reference__1_Medium_ThermodynamicState__desc_added 1
const char* Reference__1_Medium_ThermodynamicState__desc__fields[2] = {"p","h"};
struct record_description Reference__1_Medium_ThermodynamicState__desc = {
  "Reference__1_Medium_ThermodynamicState", /* package_record__X */
  "Reference_1.Medium.ThermodynamicState", /* package.record_X */
  Reference__1_Medium_ThermodynamicState__desc__fields
};

void Reference__1_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  Reference__1_Medium_ThermodynamicState* ths = (Reference__1_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
Reference__1_Medium_ThermodynamicState omc_Reference__1_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h) {
  Reference__1_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in Reference__1_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  Reference__1_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  return dst;
}
*/

void Reference__1_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  Reference__1_Medium_ThermodynamicState* src = (Reference__1_Medium_ThermodynamicState*)(v_src);
  Reference__1_Medium_ThermodynamicState* dst = (Reference__1_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
}

#define SolarTherm_Models_Sources_Weather_Metadata__desc_added 1
const char* SolarTherm_Models_Sources_Weather_Metadata__desc__fields[6] = {"name","lat","lon","elev","tzone","tstart"};
struct record_description SolarTherm_Models_Sources_Weather_Metadata__desc = {
  "SolarTherm_Models_Sources_Weather_Metadata", /* package_record__X */
  "SolarTherm.Models.Sources.Weather.Metadata", /* package.record_X */
  SolarTherm_Models_Sources_Weather_Metadata__desc__fields
};

void SolarTherm_Models_Sources_Weather_Metadata_construct_p(threadData_t *threadData, void* v_ths ) {
  SolarTherm_Models_Sources_Weather_Metadata* ths = (SolarTherm_Models_Sources_Weather_Metadata*)(v_ths);
  // ths->_name has no default value.
  // ths->_lat has no default value.
  // ths->_lon has no default value.
  // ths->_elev has no default value.
  // ths->_tzone has no default value.
  // ths->_tstart has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
SolarTherm_Models_Sources_Weather_Metadata omc_SolarTherm_Models_Sources_Weather_Metadata(threadData_t *threadData , modelica_string  in_name, modelica_real  in_lat, modelica_real  in_lon, modelica_real  in_elev, modelica_real  in_tzone, modelica_real  in_tstart) {
  SolarTherm_Models_Sources_Weather_Metadata dst;
  // TODO Improve me. No need to initalize the record members with defaults in SolarTherm_Models_Sources_Weather_Metadata_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  SolarTherm_Models_Sources_Weather_Metadata_construct(threadData, dst);
  dst._name =  in_name;
  dst._lat =  in_lat;
  dst._lon =  in_lon;
  dst._elev =  in_elev;
  dst._tzone =  in_tzone;
  dst._tstart =  in_tstart;
  return dst;
}
*/

void SolarTherm_Models_Sources_Weather_Metadata_copy_p(void* v_src, void* v_dst) {
  SolarTherm_Models_Sources_Weather_Metadata* src = (SolarTherm_Models_Sources_Weather_Metadata*)(v_src);
  SolarTherm_Models_Sources_Weather_Metadata* dst = (SolarTherm_Models_Sources_Weather_Metadata*)(v_dst);
  dst->_name = src->_name;
  dst->_lat = src->_lat;
  dst->_lon = src->_lon;
  dst->_elev = src->_elev;
  dst->_tzone = src->_tzone;
  dst->_tstart = src->_tstart;
}

#define SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState__desc_added 1
const char* SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState__desc__fields[2] = {"p","h"};
struct record_description SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState__desc = {
  "SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState", /* package_record__X */
  "SolarTherm.Models.CSP.CRS.Receivers.ReceiverSimple$receiver.Medium.ThermodynamicState", /* package.record_X */
  SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState__desc__fields
};

void SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState* ths = (SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState omc_SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h) {
  SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  return dst;
}
*/

void SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState* src = (SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState*)(v_src);
  SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState* dst = (SolarTherm_Models_CSP_CRS_Receivers__omcQReceiverSimple_24receiver_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
}

#define SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState__desc_added 1
const char* SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState__desc__fields[2] = {"p","h"};
struct record_description SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState__desc = {
  "SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState", /* package_record__X */
  "SolarTherm.Models.Fluid.Sensors.Temperature$temperature.Medium.ThermodynamicState", /* package.record_X */
  SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState__desc__fields
};

void SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState* ths = (SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState omc_SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h) {
  SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  return dst;
}
*/

void SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState* src = (SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState*)(v_src);
  SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState* dst = (SolarTherm_Models_Fluid_Sensors__omcQTemperature_24temperature_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
}

#define SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState__desc_added 1
const char* SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState__desc__fields[2] = {"p","h"};
struct record_description SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState__desc = {
  "SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState", /* package_record__X */
  "SolarTherm.Models.PowerBlocks.PowerBlockModel$powerBlock.Medium.ThermodynamicState", /* package.record_X */
  SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState__desc__fields
};

void SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState* ths = (SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState omc_SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h) {
  SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  return dst;
}
*/

void SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState* src = (SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState*)(v_src);
  SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState* dst = (SolarTherm_Models_PowerBlocks__omcQPowerBlockModel_24powerBlock_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
}

#define SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState__desc_added 1
const char* SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState__desc__fields[2] = {"p","h"};
struct record_description SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState__desc = {
  "SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState", /* package_record__X */
  "SolarTherm.Models.Storage.Tank.Tank$tankCold.Medium.ThermodynamicState", /* package.record_X */
  SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState__desc__fields
};

void SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState* ths = (SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState omc_SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h) {
  SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  return dst;
}
*/

void SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState* src = (SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState*)(v_src);
  SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState* dst = (SolarTherm_Models_Storage_Tank__omcQTank_24tankCold_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
}

#define SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState__desc_added 1
const char* SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState__desc__fields[2] = {"p","h"};
struct record_description SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState__desc = {
  "SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState", /* package_record__X */
  "SolarTherm.Models.Storage.Tank.Tank$tankHot.Medium.ThermodynamicState", /* package.record_X */
  SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState__desc__fields
};

void SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState_construct_p(threadData_t *threadData, void* v_ths ) {
  SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState* ths = (SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState*)(v_ths);
  // ths->_p has no default value.
  // ths->_h has no default value.
}
// This function should eventualy replace the default 'modelica' record constructor funcition
// that omc used to generate, i.e., replace functionBodyRecordConstructor template.
/*
SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState omc_SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState(threadData_t *threadData , modelica_real  in_p, modelica_real  in_h) {
  SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState dst;
  // TODO Improve me. No need to initalize the record members with defaults in SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState_construct
  // We should just do the allocs here and then copy the input parameters as default values instead.
  SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState_construct(threadData, dst);
  dst._p =  in_p;
  dst._h =  in_h;
  return dst;
}
*/

void SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState_copy_p(void* v_src, void* v_dst) {
  SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState* src = (SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState*)(v_src);
  SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState* dst = (SolarTherm_Models_Storage_Tank__omcQTank_24tankHot_Medium_ThermodynamicState*)(v_dst);
  dst->_p = src->_p;
  dst->_h = src->_h;
}

#ifdef __cplusplus
}
#endif

