/* Algebraic */
#include "Reference_1_model.h"

#ifdef __cplusplus
extern "C" {
#endif


/* forwarded equations */
extern void Reference_1_eqFunction_510(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_511(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_512(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_513(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_514(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_515(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_516(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_517(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_518(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_519(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_520(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_521(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_522(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_523(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_524(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_525(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_526(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_527(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_528(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_529(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_530(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_531(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_532(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_533(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_536(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_537(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_542(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_543(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_548(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_549(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_550(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_551(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_552(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_553(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_554(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_555(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_556(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_557(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_558(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_561(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_562(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_563(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_564(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_565(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_572(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_573(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_574(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_575(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_576(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_577(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_578(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_579(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_580(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_581(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_582(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_583(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_584(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_586(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_596(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_603(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_604(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_606(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_619(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_621(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_622(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_626(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_627(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_663(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_664(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_665(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_666(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_667(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_668(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_689(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_690(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_691(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_696(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_698(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_704(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_715(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_716(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_717(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_718(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_719(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_720(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_721(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_722(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_723(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_724(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_725(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_726(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_727(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_728(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_729(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_730(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_731(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_732(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_733(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_734(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_735(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_736(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_737(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_738(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_739(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_740(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_741(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_742(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_743(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_744(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_745(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_746(DATA* data, threadData_t *threadData);
extern void Reference_1_eqFunction_747(DATA* data, threadData_t *threadData);

static void functionAlg_system0(DATA *data, threadData_t *threadData)
{
  Reference_1_eqFunction_510(data, threadData);
  threadData->lastEquationSolved = 510;
  Reference_1_eqFunction_511(data, threadData);
  threadData->lastEquationSolved = 511;
  Reference_1_eqFunction_512(data, threadData);
  threadData->lastEquationSolved = 512;
  Reference_1_eqFunction_513(data, threadData);
  threadData->lastEquationSolved = 513;
  Reference_1_eqFunction_514(data, threadData);
  threadData->lastEquationSolved = 514;
  Reference_1_eqFunction_515(data, threadData);
  threadData->lastEquationSolved = 515;
  Reference_1_eqFunction_516(data, threadData);
  threadData->lastEquationSolved = 516;
  Reference_1_eqFunction_517(data, threadData);
  threadData->lastEquationSolved = 517;
  Reference_1_eqFunction_518(data, threadData);
  threadData->lastEquationSolved = 518;
  Reference_1_eqFunction_519(data, threadData);
  threadData->lastEquationSolved = 519;
  Reference_1_eqFunction_520(data, threadData);
  threadData->lastEquationSolved = 520;
  Reference_1_eqFunction_521(data, threadData);
  threadData->lastEquationSolved = 521;
  Reference_1_eqFunction_522(data, threadData);
  threadData->lastEquationSolved = 522;
  Reference_1_eqFunction_523(data, threadData);
  threadData->lastEquationSolved = 523;
  Reference_1_eqFunction_524(data, threadData);
  threadData->lastEquationSolved = 524;
  Reference_1_eqFunction_525(data, threadData);
  threadData->lastEquationSolved = 525;
  Reference_1_eqFunction_526(data, threadData);
  threadData->lastEquationSolved = 526;
  Reference_1_eqFunction_527(data, threadData);
  threadData->lastEquationSolved = 527;
  Reference_1_eqFunction_528(data, threadData);
  threadData->lastEquationSolved = 528;
  Reference_1_eqFunction_529(data, threadData);
  threadData->lastEquationSolved = 529;
  Reference_1_eqFunction_530(data, threadData);
  threadData->lastEquationSolved = 530;
  Reference_1_eqFunction_531(data, threadData);
  threadData->lastEquationSolved = 531;
  Reference_1_eqFunction_532(data, threadData);
  threadData->lastEquationSolved = 532;
  Reference_1_eqFunction_533(data, threadData);
  threadData->lastEquationSolved = 533;
  Reference_1_eqFunction_536(data, threadData);
  threadData->lastEquationSolved = 536;
  Reference_1_eqFunction_537(data, threadData);
  threadData->lastEquationSolved = 537;
  Reference_1_eqFunction_542(data, threadData);
  threadData->lastEquationSolved = 542;
  Reference_1_eqFunction_543(data, threadData);
  threadData->lastEquationSolved = 543;
  Reference_1_eqFunction_548(data, threadData);
  threadData->lastEquationSolved = 548;
  Reference_1_eqFunction_549(data, threadData);
  threadData->lastEquationSolved = 549;
  Reference_1_eqFunction_550(data, threadData);
  threadData->lastEquationSolved = 550;
  Reference_1_eqFunction_551(data, threadData);
  threadData->lastEquationSolved = 551;
  Reference_1_eqFunction_552(data, threadData);
  threadData->lastEquationSolved = 552;
  Reference_1_eqFunction_553(data, threadData);
  threadData->lastEquationSolved = 553;
  Reference_1_eqFunction_554(data, threadData);
  threadData->lastEquationSolved = 554;
  Reference_1_eqFunction_555(data, threadData);
  threadData->lastEquationSolved = 555;
  Reference_1_eqFunction_556(data, threadData);
  threadData->lastEquationSolved = 556;
  Reference_1_eqFunction_557(data, threadData);
  threadData->lastEquationSolved = 557;
  Reference_1_eqFunction_558(data, threadData);
  threadData->lastEquationSolved = 558;
  Reference_1_eqFunction_561(data, threadData);
  threadData->lastEquationSolved = 561;
  Reference_1_eqFunction_562(data, threadData);
  threadData->lastEquationSolved = 562;
  Reference_1_eqFunction_563(data, threadData);
  threadData->lastEquationSolved = 563;
  Reference_1_eqFunction_564(data, threadData);
  threadData->lastEquationSolved = 564;
  Reference_1_eqFunction_565(data, threadData);
  threadData->lastEquationSolved = 565;
  Reference_1_eqFunction_572(data, threadData);
  threadData->lastEquationSolved = 572;
  Reference_1_eqFunction_573(data, threadData);
  threadData->lastEquationSolved = 573;
  Reference_1_eqFunction_574(data, threadData);
  threadData->lastEquationSolved = 574;
  Reference_1_eqFunction_575(data, threadData);
  threadData->lastEquationSolved = 575;
  Reference_1_eqFunction_576(data, threadData);
  threadData->lastEquationSolved = 576;
  Reference_1_eqFunction_577(data, threadData);
  threadData->lastEquationSolved = 577;
  Reference_1_eqFunction_578(data, threadData);
  threadData->lastEquationSolved = 578;
  Reference_1_eqFunction_579(data, threadData);
  threadData->lastEquationSolved = 579;
  Reference_1_eqFunction_580(data, threadData);
  threadData->lastEquationSolved = 580;
  Reference_1_eqFunction_581(data, threadData);
  threadData->lastEquationSolved = 581;
  Reference_1_eqFunction_582(data, threadData);
  threadData->lastEquationSolved = 582;
  Reference_1_eqFunction_583(data, threadData);
  threadData->lastEquationSolved = 583;
  Reference_1_eqFunction_584(data, threadData);
  threadData->lastEquationSolved = 584;
  Reference_1_eqFunction_586(data, threadData);
  threadData->lastEquationSolved = 586;
  Reference_1_eqFunction_596(data, threadData);
  threadData->lastEquationSolved = 596;
  Reference_1_eqFunction_603(data, threadData);
  threadData->lastEquationSolved = 603;
  Reference_1_eqFunction_604(data, threadData);
  threadData->lastEquationSolved = 604;
  Reference_1_eqFunction_606(data, threadData);
  threadData->lastEquationSolved = 606;
  Reference_1_eqFunction_619(data, threadData);
  threadData->lastEquationSolved = 619;
  Reference_1_eqFunction_621(data, threadData);
  threadData->lastEquationSolved = 621;
  Reference_1_eqFunction_622(data, threadData);
  threadData->lastEquationSolved = 622;
  Reference_1_eqFunction_626(data, threadData);
  threadData->lastEquationSolved = 626;
  Reference_1_eqFunction_627(data, threadData);
  threadData->lastEquationSolved = 627;
  Reference_1_eqFunction_663(data, threadData);
  threadData->lastEquationSolved = 663;
  Reference_1_eqFunction_664(data, threadData);
  threadData->lastEquationSolved = 664;
  Reference_1_eqFunction_665(data, threadData);
  threadData->lastEquationSolved = 665;
  Reference_1_eqFunction_666(data, threadData);
  threadData->lastEquationSolved = 666;
  Reference_1_eqFunction_667(data, threadData);
  threadData->lastEquationSolved = 667;
  Reference_1_eqFunction_668(data, threadData);
  threadData->lastEquationSolved = 668;
  Reference_1_eqFunction_689(data, threadData);
  threadData->lastEquationSolved = 689;
  Reference_1_eqFunction_690(data, threadData);
  threadData->lastEquationSolved = 690;
  Reference_1_eqFunction_691(data, threadData);
  threadData->lastEquationSolved = 691;
  Reference_1_eqFunction_696(data, threadData);
  threadData->lastEquationSolved = 696;
  Reference_1_eqFunction_698(data, threadData);
  threadData->lastEquationSolved = 698;
  Reference_1_eqFunction_704(data, threadData);
  threadData->lastEquationSolved = 704;
  Reference_1_eqFunction_715(data, threadData);
  threadData->lastEquationSolved = 715;
  Reference_1_eqFunction_716(data, threadData);
  threadData->lastEquationSolved = 716;
  Reference_1_eqFunction_717(data, threadData);
  threadData->lastEquationSolved = 717;
  Reference_1_eqFunction_718(data, threadData);
  threadData->lastEquationSolved = 718;
  Reference_1_eqFunction_719(data, threadData);
  threadData->lastEquationSolved = 719;
  Reference_1_eqFunction_720(data, threadData);
  threadData->lastEquationSolved = 720;
  Reference_1_eqFunction_721(data, threadData);
  threadData->lastEquationSolved = 721;
  Reference_1_eqFunction_722(data, threadData);
  threadData->lastEquationSolved = 722;
  Reference_1_eqFunction_723(data, threadData);
  threadData->lastEquationSolved = 723;
  Reference_1_eqFunction_724(data, threadData);
  threadData->lastEquationSolved = 724;
  Reference_1_eqFunction_725(data, threadData);
  threadData->lastEquationSolved = 725;
  Reference_1_eqFunction_726(data, threadData);
  threadData->lastEquationSolved = 726;
  Reference_1_eqFunction_727(data, threadData);
  threadData->lastEquationSolved = 727;
  Reference_1_eqFunction_728(data, threadData);
  threadData->lastEquationSolved = 728;
  Reference_1_eqFunction_729(data, threadData);
  threadData->lastEquationSolved = 729;
  Reference_1_eqFunction_730(data, threadData);
  threadData->lastEquationSolved = 730;
  Reference_1_eqFunction_731(data, threadData);
  threadData->lastEquationSolved = 731;
  Reference_1_eqFunction_732(data, threadData);
  threadData->lastEquationSolved = 732;
  Reference_1_eqFunction_733(data, threadData);
  threadData->lastEquationSolved = 733;
  Reference_1_eqFunction_734(data, threadData);
  threadData->lastEquationSolved = 734;
  Reference_1_eqFunction_735(data, threadData);
  threadData->lastEquationSolved = 735;
  Reference_1_eqFunction_736(data, threadData);
  threadData->lastEquationSolved = 736;
  Reference_1_eqFunction_737(data, threadData);
  threadData->lastEquationSolved = 737;
  Reference_1_eqFunction_738(data, threadData);
  threadData->lastEquationSolved = 738;
  Reference_1_eqFunction_739(data, threadData);
  threadData->lastEquationSolved = 739;
  Reference_1_eqFunction_740(data, threadData);
  threadData->lastEquationSolved = 740;
  Reference_1_eqFunction_741(data, threadData);
  threadData->lastEquationSolved = 741;
  Reference_1_eqFunction_742(data, threadData);
  threadData->lastEquationSolved = 742;
  Reference_1_eqFunction_743(data, threadData);
  threadData->lastEquationSolved = 743;
  Reference_1_eqFunction_744(data, threadData);
  threadData->lastEquationSolved = 744;
  Reference_1_eqFunction_745(data, threadData);
  threadData->lastEquationSolved = 745;
  Reference_1_eqFunction_746(data, threadData);
  threadData->lastEquationSolved = 746;
  Reference_1_eqFunction_747(data, threadData);
  threadData->lastEquationSolved = 747;
}
/* for continuous time variables */
int Reference_1_functionAlgebraics(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

#if !defined(OMC_MINIMAL_RUNTIME)
  if (measure_time_flag) rt_tick(SIM_TIMER_ALGEBRAICS);
#endif
  data->simulationInfo->callStatistics.functionAlgebraics++;

  functionAlg_system0(data, threadData);

  Reference_1_function_savePreSynchronous(data, threadData);
  
#if !defined(OMC_MINIMAL_RUNTIME)
  if (measure_time_flag) rt_accumulate(SIM_TIMER_ALGEBRAICS);
#endif

  TRACE_POP
  return 0;
}

#ifdef __cplusplus
}
#endif
